### ISSUE TITLE
phone display - teams - more button hard to read

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#119]
When a user sees their profile and clicks on teams, the get the below screen. When I try to hover over "more' or click on it - -the text comes and goes, its hard to keep my finger on it and read the "more" text description 

Ideas on how to fix this?
![Mass Energize phone teams :more button](https://user-images.githubusercontent.com/60329553/75746424-3afc4200-5ce8-11ea-8891-cc88afcf1406.png)

**Comment by BradHN1** [comment]
This may be a general problem with the hover-over on the iphone.  I can't get it to show information that is readable.

**Comment by Pongo1** [comment]
Yes, phones dont have the hover functionality.  So when there is a hover function on anything, you would have to click it to do what hovering would have done. However, we dont see the hovering effect even after we have clicked on phone view too because usually whatever we are clicking has been set to do something when wd click it. So it just ignores hovering in general... lol :)
