### ISSUE TITLE
Event card: data config and (on home page) one line description?

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#189]
Can we make space on the event cards on the home page for the one sentence description that does show up on the card on the all events page?
![image](https://user-images.githubusercontent.com/30277868/79874438-5fa29b00-83b6-11ea-98a3-dd270328af58.png)
We can clear a lot of space for it by reconfiguring the date whcih at the moment takes up two lines.
e also need to do something about the commas in the location line.

**Comment by jkatofsky** [comment]
Made this change [here](https://github.com/massenergize/frontend-portal/commit/83f89d797e2b25b6e7ca74a609827ecca8214bef). Next, I will do the [date formatting changes](https://github.com/massenergize/frontend-portal/issues/167) and then make a PR from my josh-events-changes branch containing both fixes.

**Comment by jkatofsky** [comment]
I have changed the way that dates and locations display, added an event summary, and changed some of the font sizes and text formatting. Here's an example showing the difference between the current event cards on the homepage and my version:

<img width="300" alt="Screen Shot 2020-05-19 at 4 41 26 PM" src="https://user-images.githubusercontent.com/13226824/82377416-9d183980-99f1-11ea-909e-e0c3c75b9354.png"><img width="300" alt="Screen Shot 2020-05-19 at 4 41 21 PM" src="https://user-images.githubusercontent.com/13226824/82377448-a7d2ce80-99f1-11ea-971d-1507474d2357.png">


<img width="300" alt="Screen Shot 2020-05-19 at 4 59 36 PM" src="https://user-images.githubusercontent.com/13226824/82377749-2596da00-99f2-11ea-98a6-48acb3320d78.png"><img width="300" alt="Screen Shot 2020-05-19 at 4 59 14 PM" src="https://user-images.githubusercontent.com/13226824/82377769-2e87ab80-99f2-11ea-8b40-4e5b4d13391d.png">

For the locations I removed all unnecessary commas added by our front end; the extra comma that remains after "My Neighborhood Farm" is because a comma was inputted after that location's unit on the admin portal - not because of the front-end. This must be changed by an admin.

Open to any and all feedback!

@BradHN1 @kaatvds

**Comment by kaatvds** [comment]
Date works, looks good! However, when an event is community-wide it would be great to put in only the town and no street address and unit #. When not it says "null" on the card.
![Screenshot (527)](https://user-images.githubusercontent.com/30277868/82740520-71f65880-9d17-11ea-9802-9758da764ac2.png)
