### ISSUE TITLE
Actions completed and todo don't show up in development, and cant be added.

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#298]
In current development branch code, sign in to Nowhere or another community, and my actions completed aren't shown.

Tru to add an action to Todo or Done, and no action added.

Error in javascript console:
TypeError: e.todo is not iterable
    at user (userReducer.js:55)
    at redux.js:459
    at v (redux.js:213)
    at index.js:11
    at dispatch (redux.js:638)
    at userActions.js:59
    at index.js:8
    at Object.reduxAddToTodo (redux.js:477)
    at ActionsPage.js:198:

**Comment by jkatofsky** [comment]
`users.actions.todo.list` and `users.actions.completed.list` are giving sign-in errors. This means that the store data is undefined for those, meaning that the completed actions don't display properly _and_ the updating of actions TODO/DONE in Redux provides an error because the previous state is undefined.

**Comment by jkatofsky** [comment]
A symptom of v2 auth routes, says @BradHN1 . Hopefully will be fixed by the auth changes.

**Comment by kaatvds** [comment]
to do and done it buttons DO work on all actions page but not on indiv action page

**Comment by BradHN1** [comment]
Fixed on indiv action page - branch BHN-testing
