### ISSUE TITLE
DEV: indiv Team page: bar graph says "The actions data for this team could not be loaded." 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#313]
![image](https://user-images.githubusercontent.com/30277868/92160680-64179f80-edfd-11ea-8d4e-f333be7e0b82.png)

**Comment by frimpongopoku** [comment]
Hi @kaatvds , the message you saw here was just a precaution @jkatofsky  took, in case the backend does not respond properly when we are calling for data. If he hadn't placed this check, you would probably have seen the scary blank screen you are used to now, LOOL! 🤣 🤣  . This is a much better way of handling things.
More importantly, I think this ticket also came up because of  the changes Sam hadn't finished yet. Now that he is done, things are working nicely 🔥 . I have tested this.

So, I will close this, and move to deployed.

NICE WORK @jkatofsky  🎊  🥂  🍻
