### ISSUE TITLE
logo on top bar: bigger

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#36]
We'll need to discuss this. Newton requests their logo is larger

**Comment by BradHN1** [comment]
Same as bug 1263 in the tracker: Community logo can overlaps picture

Instructions on community logos suggests logo should be a certain size (150 x 57.88).  This is ok if using one of the Energize logos but for groups who have existing logos the aspect ratio (horizontal vs vertical) will be different.  For example the Cooler Concord logo is 190x100 and doesn't want to be shrunk further.  The portal resizes it to width 150 (150x79) but since 79>57.88 it overlaps the picture.  This can be fixed by editing padding (there is 18px padding above and below).

**Comment by kaatvds** [comment]
Hi Brad, this is a little bit different. Newtonians would like their Green Newton to be larger to have better GreenNewton branding (sacrificing Events tab in top bar menu of need be). I said we'd see how others feel - hence no label on this one, just logged for later.

**Comment by BradHN1** [comment]
I think it is exactly the same.  We want our logo to be bigger as well.  And it is important, you can’t read it if you shrink it so it fits within the band.

++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)

**Comment by BradHN1** [comment]
Improved the fit of logos with somewhat taller aspect than the Energize logos.  Certainly can do better than this, but need to test out.

**Comment by BradHN1** [comment]
Needs testing by Newton group

**Comment by BradHN1** [comment]
@kaatvds - I think this would be adequately tested if the Green Newton logo looks good enough.  Do you have a copy of that, or should we reach out to them?

**Comment by kaatvds** [comment]
Can you test it out in DEV with the cooler concord logo?

**Comment by BradHN1** [comment]
I had fixed this issue on 1/29 but apparently that fix was temporary since now broken in Dev.  See the overlap of the Icon in the Nowhere community:

<img width="764" alt="Screen Shot 2020-03-19 at 9 26 14 PM" src="https://user-images.githubusercontent.com/12800484/77128920-6725fb80-6a28-11ea-8537-7d3c8944d43f.png">

**Comment by BradHN1** [comment]
Testing @BradHN1 @OrlyStrobel

**Comment by jkatofsky** [comment]
Introduced a bug when opening the burgered menu. I'm on it

**Comment by OrlyStrobel** [comment]
I am unsure about this one (tested on computer and mobile in prod) because the overlapping logo problem is definitely fixed, but the logo seems small still? Though, I do not know how this compares to what the logo looked like back in January or if this is even a concern anymore. @BradHN1 

![Screen Shot 2020-07-10 at 11 23 44 AM](https://user-images.githubusercontent.com/65621001/87170803-d22d6380-c29f-11ea-8e62-d8ac1932e940.png)

**Comment by jkatofsky** [comment]
This may have to do with the dimensions and nature of the image that GreenNewton uploaded - the goal of this change is to have the navbar expand vertically when the source images are taller
