### ISSUE TITLE
Dev+Prod : Community site shows on non-sandbox when not published.

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#370]
If a community site is not live, it should not show up if you aren't in the sandbox.  It is important to be able to take a site down by making it not live.

**Comment by kaatvds** [comment]
Not sure if this works. Or might be misunderstanding the issue. the community "Framingham" is not live. I see it in  sandox. But I also see it when I enter "https://community-dev.massenergize.org/Framingham"...

**Comment by BradHN1** [comment]
Changing IS_PROD to !IS_SANDBOX to fix this

**Comment by frimpongopoku** [comment]
Hi brad,
Its because the check is only done when you are in prod mode. Sandbox will
always show it even if its not live and dev mode will also show it if you
have a link but not as a part of the list of communities on the landing
page. (Unless you think I should put the check in dev mode tooo???)



-Frimpong

**Comment by BradHN1** [comment]
@frimpongopoku - I fixed this two days ago, did you review the PR  https://github.com/massenergize/frontend-portal/pull/551
