### ISSUE TITLE
DEV: join/leave teams broken

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#375]
chrome
get error message
![image](https://user-images.githubusercontent.com/60662056/96041364-b2c34b00-0e39-11eb-995d-b1e2e52936e7.png)

join team error message:
![image](https://user-images.githubusercontent.com/60662056/96041748-501e7f00-0e3a-11eb-95b4-03c88a061d5b.png)

**Comment by BradHN1** [comment]
Fixed in branch BHN-teams-bugs

**Comment by frimpongopoku** [comment]
Hi @kaatvds , this is backend stuff. I think @BradHN1  fixed already. Maybe he hasnt deployed yet that is why. Please see the comment above.

**Comment by kaatvds** [comment]
it seems to work but this "Contact Admin of [name]" is confusing to the user. What does this mean? Is the user asked to contact the admin? i think more explan is needed: 
"The admin of [name] will receive a notification that you joined" IF that is the case.... (It doesn't look like it because I as he admin did not get a message)

**Comment by BradHN1** [comment]
Improved the message to make it less confusing.
