### ISSUE TITLE
DEV: testimonial page

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#384]
Would be better when you open the testimonial, go to a page (with is own url), just like actions or events, not a modal, 

Show the photo not a little tiny circle photo but same as for events

current BUG: Testimonial modal is showing todays date, not the date of the testimonial - make sure on the page right date is shown.

**Comment by kaatvds** [comment]
I get an error message on all indiv testimonial pages. Screenshot with console below:

![image](https://user-images.githubusercontent.com/30277868/97015693-df522380-1519-11eb-9703-95f36192eb0b.png)

**Comment by frimpongopoku** [comment]
Ooooh yes, yes. This is actually known. I will create a ticket on the API portal so this is clear. The problem is actually with the API. 
Its simply that we are not allowed access to testimonials when we are not signed in. That obviously should not be; I told Sam, and he said he will fix. My bad, I should have created the ticket earlier. I am going to do that now. @kaatvds
