### ISSUE TITLE
Team modal sizing issues 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#451]
Ellen: When I fill  it out there is no button to hit submit, I don't see that button on my screen, I am on a mac using Chrome at 100%, I can see the submit button when I  make my browser= 90%

**Comment by jkatofsky** [comment]
More general summary of the issues:

- on the one team page, the modals seem to be offset too low down in the viewport (compare with the create team modal to see the difference), which causes some parts to be unreachable for the contact admin and edit team modals
- the join/leave and contact admin modals get way too skinny as the viewport gets skinnier

paging @frimpongopoku to see if he can take a look at this because I couldn't wrap my head around how the modals are sized now that we are using `MEModal`. maybe he will have more luck
