### ISSUE TITLE
New UI Wave - Horizontal Filter Box

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/frontend-portal#526]
UI information can be found here [https://docs.google.com/document/d/1Tww_-U7TShZbB2Qs7BNvGqw6GjyDwME4UAoTMr42eEo/edit](url)

**Comment by BradHN1** [comment]
These are my comments on the prototype filter bar currently deployed to dev:

1. the bar should have a color, not just be text on the white background
2. for category, select none or one, not multiple.  Same for Cost and Impact
3. Don't put the little baloons below the bar to show what was selected.  Instead the bar should say:
    Category:Any (if none selected) or Category:Solar (if solar selected, etc).  same for cost and impact..
4. As issue 532 indicates, the filters should be a logical AND, meaning if you select Home and High impact, it should show actions which are Home AND high impact.  (currently works as OR).

**Comment by frimpongopoku** [comment]
Noted @BradHN1 . I shall implement these suggestions ASAP. 
What color should the bar be though??? Do you have any ideas....??? Or I should try something and show you?

**Comment by BradHN1** [comment]
To choose a color, we’ll need to have a focus group work on this.  (Just kidding of course)_  I think if you pick something that goes along with the platform colors but not orange that would be a good start, and we can tweak it from there.

**Comment by BradHN1** [comment]
@frimpongopoku - For the filter bar, for each tag collection (like "I am a..."), when you create the dropdown menu with the tag options, only show those options which have an action that has that tag.  For example, if there is no action tagged with "Student", you can eliminate that from the list.  Then, if the list has no remaining options (nothing tagged for those choices) you shouldn't show the pull down.   This logic will extend to events, service providers, testimonials as well.

**Comment by frimpongopoku** [comment]
Noted @BradHN1 , incoming. Lol!

**Comment by BradHN1** [comment]
Here are comments on the filter bar from today (group discussion):
1.  On filter bar, order of tag collections should be (from left to right):  "I am a...", "Category", "Impact", "Cost"
2. When a filter not set, have the tag collection name shown with a carat ^
3. When a filter set, replace the tag collection name with the tag, and replace the carat with an x.  So "Home Energy x" instead of "Category: Home Energy".  When you click on "Home Energy x" it opens the pull down, and if you quick click it clears the filter.
4. Instead of "None" on the pull down, replace with "--"
5. Eliminate the "Filters Set" indicator
6. Add the "Search" field to the right of the filters.

**Comment by frimpongopoku** [comment]
Noted @BradHN1 🤝

**Comment by BradHN1** [comment]
Looking good!
Two small comments:
* the search works well except if you enter capitalized words, then it doesn't.  I think you should convert to lowercase before search;
* the "clear filters" can overlap the leftmost tag.  Should be some padding or way to make it not overlap.

**Comment by kaatvds** [comment]
comments on deploy 3/29: 

1. - the footer is stuck: it takes up a lot of real estate: please put it back down at the bottom of the page.
2. - It is possible to have the filter options remain in the same place as you click them: there's a lot of movement left and right as you click them right now, which is confusing.
3. - Also, there is quite a bit of horiz space there; can the filters be further apart?
4. willl the sentence at the top be customizable? 
5. Not sure if in this sprint to prod we are also planning to have the two side panels (done it, to do) work and tally up before someone signs up (and when they leave: ask them to save by signing up). If not, then is it possible to have the two panels saying zero for done it and to do, with some text that states they need to sign up, instead of the sentence, "Sign In to add actions to your todo list or to mark them as complete", which isn't really interesting and inviting?

**Comment by frimpongopoku** [comment]
Can I please get screen shots of all the things going on, cos I have none of the above mentioned on my pc 🤣 🤣 🤣  @BradHN1 @kaatvds . Thanks

**Comment by BradHN1** [comment]
I'm adding three tickets to customize the Page Titles, requiring changes to community portal, admin portal

**Comment by kaatvds** [comment]
![image](https://user-images.githubusercontent.com/30277868/112863827-4190f080-9085-11eb-801d-24d7c973777c.png)

**Comment by BradHN1** [comment]
@frimpongopoku - some feedback on the filter bar
1. The filter bar should be minimum thickness, with the search in the same line with the tag selection, to the right of the tags.
2. For mobile at least we want the bar to be left-right swipeable.  Look at google.com search page, the menu bar with "All Maps Videos" etc.  This swipes the way we want it to.
3. We don't want the burger menu showing up, which opens a modal which blocks everything.  Just the swipeable bar.

**Comment by frimpongopoku** [comment]
Hi @BradHN1  I am not sure about what you mean by "minimum thickness"?? 
Could you calrify..?

But, about the bar looking like google, yeah, that one can be done 🤗

**Comment by BradHN1** [comment]
It is about how much space the bar takes up.  If you put search on a different line, the bar takes twice as much space.  With option 2, the bar take three times as much space as needed.

**Comment by frimpongopoku** [comment]
Well noted. I will play with smaller laptop dimensions then, cos the search box never moves on to the next line on my screen. Thanks.

**Comment by kaatvds** [comment]
The whole idea about moving the filter is that it takes up less space, not more. Moving it up means it takes a bite out of the most important part of that page: the action cards, and that is unavoidable. But it needs to be minimal (and not many use it anyway). 
I'm wondering if you can put the filter bar (on laptop at least) "higher up", that is, at the same level as the nav bar. That would give it the full width of the screen (not just the width of the action cards section), and then everything could fit on one think line.
It would also (I think) fix the vertical alignment of the personal score boxes.

**Comment by frimpongopoku** [comment]
Yes @kaatvds  that can easily be done.
