### ISSUE TITLE
URL Routes to filtered views on Actions/Events/Testimonials/Service providers

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#539]
We want to be able to share links to get filtered views on these pages.
Include the Facebook share

**Comment by frimpongopoku** [comment]
Hi @BradHN1 , thanks, I will look into why filters dont clear when "clear filters" is used. 

About your second issue, I actually **do** understand what you mean, but I chose to go this way  due to the following reasons: 
1. We know all tags, and tag collections on the platform are dynamic. Sadmins can create more and edit names and what not at anytime. What happens if Sadmins decide that "Impact" should now be called "Burgers"...? 😂😂  Any routes that have been shared before with filters will not select "Category" anymore when a user visits. That is why I chose to go with Ids -- that never changes, and is a more trustworthy key to use in filtering. 
2. I also strongly advise that we focus on how strong the mechanism for identifying filters from the URL bar is, than trying to make the entire URL make sense to the user....? I understand that making the URL understandable forms part of the good UX we are aiming for, but that is already achieved. The main routes that we want users to find easy, and to able to remember with ease are already achieved : `/actions, /events/3, /teams... etc` -- easy!. URL search params are not part of things that users are meant to remember, though its nice to have it make sense. In fact, users are not meant to be tinkering with the filter parameters in the URL directly. We only need them to use the interface we created to generate what kind of filters they want; then -- copy.
