### ISSUE TITLE
Photo does not display correctly

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#77]
ISSUE 1229
Reported on Tue Dec 31 2019 18:05:50 GMT-0500 (EST)
Reported by Aimee M Powelka(aimee.powelka@gmail.com)
PRIORITY = High
STATUS = InProgress - Submitted 

Site Url: https://community-dev.massenergize.org/SFDemo/actions

Description:
Same photo was loaded for Events and Actions. It appears correctly for events, but is cut off for actions.

User Role: Community Admin
Attachments: https://drive.google.com/open?id=1a-CKWcRNB0AqotGK2LTZ6lKFyVsVoVtB
Notes: in progress

**Comment by Pongo1** [comment]
HI @kaatvds  the problem is from the container it has been given on the actions page. The image displays better on events page because on the events card, the image container has been given dimensions  that most images can fit into. On the actions page, the height of the image container is very short, so to maintain the structure of the image, we had to use "cover" which will just allow a user to get a glimpse of what the action is while still maintaining the admin's intended size, so when they click, they can see the full image on the actions page. We can make the image container taller, but in the end, the action cards will just become LONG and weird. In future, maybe, while uploading on the backend, we can make a copy of the uploaded image and resize to fit the dimensions for only the actions page -- or we will just come up with a new design for the action page and action card if we have to.

**Comment by kaatvds** [comment]
Hi Frimpong, the actions images are fine. i actually designed most to fit. The issue with images is more for the service provider images. All these people's logos are different. Would be great just to have  ideal format. Will make separate issue for that.
