### ISSUE TITLE
Implement password-less sign in

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#792]
Creating profiles with passwords is barrier
Firebase (which we use for authentication) allows "Email link (passwordless sign-in)" which I've enabled for the dev site to test.

The following web page explains some changes we would need to implement to take advantage of it:
https://firebase.google.com/docs/auth/web/email-link-auth?authuser=0

Additionally, we need to redo the sign-up page to make it inviting to choose this method, but requiring password signi-in for admin accounts.

**Comment by Davidjwkinghorn** [comment]
Yet to do: 
- Resolve UI flow and fix bugs with sign in method detection
- manually test various flows to ensure nobody loses their account access.
- Implement password-less sign in for admin-portal (this should be released at the same time as on the frontend-portal Otherwise this might cause admins to lose access to the admin portal until this is implemented)
- Discuss options for reversing password-less auth. This needs discussion since it may not be clear to users who try password-less auth that this wipes their passwords and that they can only use email links from then on.

**Comment by Davidjwkinghorn** [comment]
It seems that Firebase doesn't have a way to create a user without some kind of password. I think for a workaround we could randomly generate a password secretly and use it to create the account. Immediately after the account is made we can activate password less sign in for the user. Then later the user could set a password later to override this or only log in with an email link and never know about the password.

Do you have any thoughts on this @Opoku-Agyemang?

https://stackoverflow.com/questions/57778372/firebase-admin-how-to-create-user-with-passwordless-signin

**Comment by BradHN1** [comment]
@Davidjwkinghorn  - this is what I want to see on the Sign-in page:

Welcome!
Sign in with your name and password **if you have one**.

Name
Password

**Forgot my password**    << this is essential, don't leave it out
**click here** to sign in without a password. or use your Google or Facebook profile to sign-in.

**Comment by BradHN1** [comment]
When I click the envelope without entering an email it says "The email address is badly formatted".  It should say, please enter the email address

**Comment by BradHN1** [comment]
When I enter an email like info@concordcan.org, it says Domain not whitelisted by project

**Comment by Davidjwkinghorn** [comment]
I had it so it would hide the forgot password link unless we detected that a user used a password to log in. I can make that static.

Where it says "The email address is badly formatted" I have tried disabling the button until something is entered, but that doesn't work. I'll have to find some other solution.

When it says "Domain not whitelisted" I have no idea what that is about. It's definitely a Firebase issue. It could be something in the Firebase portal that needs tweaking, but to my knowledge nothing I've done should change how that works. It's possible Firebase restricts which domains can be used for password less sign in.

**Comment by Davidjwkinghorn** [comment]
My most important goal right now is getting the main sign in button to work with both password-less and with a password. I'm having an issue now where the page just reloads when you hit submit seemingly for no reason. I have resolved most other issues now apart from the submit button so I'm planning on going back to the firebase-email-auth branch and manually adding my fixes again to try and see what is broken.

**Comment by Davidjwkinghorn** [comment]
Currently there is an issue with a user being promoted multiple times to reenter their email address after clicking an email link. If the user has clicked the link in the same browser the email address should have been stored and the this prompt should not show up. However, the function that handles this (completeSignInWithEmail()) is called a few times. Some of those are called after the email address that is stored is wiped from the browser resulting in multiple prompts. The user is still able to sign in, even by clicking cancel on each prompt, as long as they were in the same browser as where they tried to sign in. 

The root cause of this issue is the fact that the completeSignInWithEmail() is called multiple times. Currently it is called in componentDidMount(), but I am seeking alternative options.
