### ISSUE TITLE
Fix pending issues with ProductTour

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-portal#795]
- [x] "Take the tour" btn (navbar) displays tour when clicked
- [ ] Back btn can return to the prior page (e.g. from team to impact)
- [x] Tour keeps resuming when new pages are visited after skipping the tour - mainly happened in chrome incognito mode
- [x] Make all "got it" btns tied to links work when users hit them using keyboard. Rn it closes the tour
- [x] Shout down the tour if the user is signed in
- [x] Home page - Spotlight should include only the panel, not the community description
- [x] Make the tour skip teams page if no teams exist
- [x] Team page - tour shouldn't close if the user clicks on overlay/gray area
- [x] Home page - if the user closes the first frame it should close the tour entirely. Right now the second frame shows up anyways even when seen_tour == true. This causes that if user clicks got it on the second frame it goes nowhere 
- [ ] TourHandler - it needs to make the tour close when more than 1 step is defined. Maybe adding setTimeOut?
- [x] Signup page - button that goes to the homepage should close the whole tour
- [x] Actions page - delete random comma added by accident
- [x] NavBar - Make that the "take the tour" option on navBar always restart the tour w/o needing to refresh the page

More info about the package can be found here:
https://github.com/gilbarbara/react-joyride-demo/blob/master/src/Controlled/index.tsx
https://react-joyride.com/controlled

**Comment by frimpongopoku** [comment]
Back button returning to tour on previous page cannot happen, and that is only because we do not control when the back button is triggered to show. 

After going through joy-ride docs, and its implementations, it looks like the back button on the tour is only triggered when there is more than one step in the product tour steps on the same page.  

Thats the only time it shows a "back" button which can then be disabled if we want, or overridden in terms of design.

And for this part of the ticket _"TourHandler - it needs to make the tour close when more than 1 step is defined. Maybe adding setTimeOut?"_

I dont understand what needs to be done, so anyone care to explain.... or we leave this?

**Comment by BradHN1** [comment]
@frimpongopoku - Kaat and I made a further decision on the tour: 

from the one action page, instead of going to the impact page to show the donut graphs, it should go back to the home page to show those graphs.  

Then, instead of going to the sign-in page to talk about registering, it should stay on the home page, pointing to the sign-in button, and the message should be “For taking actions that are counted, or joining a team, you can sign-in with just your email.”  Then the tour should just end, leaving the user where they started.
